name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-os-boost:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev libboost-thread-dev libboost-serialization-dev libboost-program-options-dev
    - name: Prepare
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

  build-local-boost:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.6
      with:
        path: boost_1_57_0.tar.gz
    - name: Build
      run: ./build.sh
