name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt-get install -y libboost-all-dev
    - name: Prepare
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
